/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.telas.view;

/**
 *
 * @author Lidia
 */
public class cadastroview extends javax.swing.JFrame {

    /**
     * Creates new form cadastroview
     */
    public cadastroview() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bv1 = new javax.swing.JButton();
        bcad1 = new javax.swing.JButton();
        cnomec = new javax.swing.JTextField();
        cemail1 = new javax.swing.JTextField();
        csenha1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bv1.setContentAreaFilled(false);
        bv1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(bv1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 32, 28));

        bcad1.setContentAreaFilled(false);
        bcad1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(bcad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 327, 120, 40));

        cnomec.setBackground(new java.awt.Color(254, 168, 0));
        getContentPane().add(cnomec, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 310, 40));

        cemail1.setBackground(new java.awt.Color(254, 168, 0));
        cemail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cemail1ActionPerformed(evt);
            }
        });
        getContentPane().add(cemail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 198, 310, 40));

        csenha1.setBackground(new java.awt.Color(254, 168, 0));
        getContentPane().add(csenha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 310, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ref/Cadastro.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cemail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cemail1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cemail1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastroview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcad1;
    private javax.swing.JButton bv1;
    private javax.swing.JTextField cemail1;
    private javax.swing.JTextField cnomec;
    private javax.swing.JPasswordField csenha1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
