/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.telas.view;

/**
 *
 * @author Lidia
 */
public class loginview extends javax.swing.JFrame {

    /**
     * Creates new form loginview
     */
    public loginview() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bv = new javax.swing.JButton();
        bent2 = new javax.swing.JButton();
        bcad = new javax.swing.JButton();
        cemail = new javax.swing.JTextField();
        csenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bv.setContentAreaFilled(false);
        bv.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bvActionPerformed(evt);
            }
        });
        getContentPane().add(bv, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 30, 20));

        bent2.setContentAreaFilled(false);
        bent2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(bent2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 110, 40));

        bcad.setContentAreaFilled(false);
        bcad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(bcad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 120, 40));

        cemail.setBackground(new java.awt.Color(254, 168, 0));
        cemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cemailActionPerformed(evt);
            }
        });
        getContentPane().add(cemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 310, 40));

        csenha.setBackground(new java.awt.Color(254, 168, 0));
        getContentPane().add(csenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 202, 310, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ref/Login.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bvActionPerformed

    private void cemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cemailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bcad;
    private javax.swing.JButton bent2;
    private javax.swing.JButton bv;
    private javax.swing.JTextField cemail;
    private javax.swing.JPasswordField csenha;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
